# Generated by Django 4.2.1 on 2023-06-16 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=datetime.datetime(2023, 6, 16, 14, 41, 1, 566678, tzinfo=datetime.timezone.utc), max_length=254, verbose_name='E-Posta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2023, 6, 16, 14, 41, 5, 310950, tzinfo=datetime.timezone.utc), max_length=80, verbose_name='Ad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2023, 6, 16, 14, 41, 7, 62636, tzinfo=datetime.timezone.utc), max_length=80, verbose_name='Soyad'),
            preserve_default=False,
        ),
    ]
