# Generated by Django 4.2.1 on 2023-06-16 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/profile_photos/'),
            preserve_default=False,
        ),
    ]
