# Generated by Django 4.2.1 on 2023-06-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_notebook_delete_notebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
