# Generated by Django 4.2.1 on 2023-06-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_group', to='notebooks.notebook')),
                ('taskIds', models.ManyToManyField(related_name='task_group', to='notebooks.tasks')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
