# Generated by Django 4.2.1 on 2023-06-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0005_tasks_taskgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='content',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.TextField(),
        ),
    ]
