# Generated by Django 4.2.1 on 2023-06-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0006_remove_tasks_content_alter_tasks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='taskIds',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='notebooks.taskgroup'),
        ),
    ]
