# Generated by Django 4.2.1 on 2023-06-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0007_remove_taskgroup_taskids_tasks_task_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='userIds',
            new_name='user_ids',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='notebookId',
            new_name='notebook_id',
        ),
        migrations.RenameField(
            model_name='taskgroup',
            old_name='notebookId',
            new_name='notebook_id',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='notebookId',
            new_name='notebook_id',
        ),
        migrations.AddField(
            model_name='notebook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='notes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silme Tarihi'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ekleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ekleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ekleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ekleme Tarihi'),
        ),
    ]
