# Generated by Django 4.2.1 on 2023-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0008_rename_userids_notebook_user_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='taskgroup',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='user_ids',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='notebook_id',
            new_name='notebook',
        ),
        migrations.RenameField(
            model_name='taskgroup',
            old_name='notebook_id',
            new_name='notebook',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='notebook_id',
            new_name='notebook',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task_group_id',
            new_name='task_group',
        ),
        migrations.AlterField(
            model_name='notebook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncelleme Tarihi'),
        ),
    ]
