# Generated by Django 4.2.1 on 2023-06-14 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebooks', '0010_alter_tasks_options_tasks_rank_alter_tasks_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='creator_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_user_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
