# Generated by Django 4.2.1 on 2023-06-14 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebooks', '0011_tasks_creator_user_tasks_responsible_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='creator_user',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='notes',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
