# Generated by Django 4.2.1 on 2023-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0013_alter_notebook_options_alter_notes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
